name: CAMDA25
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy==1.26
  - pandas=2.2
  - pip=24.3.1
  - scikit-learn==1.6
  - scipy==1.14
  - tqdm=4
  - pip:
      - click==8
      - PyYAML
      - statsmodels==0.14
      - torch==2.6.0 --extra-index-url https://download.pytorch.org/whl/cu118
      - imbalanced-learn==0.13